### PR TITLE
Rockstar Speakers

### PR DESCRIPTION
**Pull request by pAditya198**
Screenshot (92)

Previous Speakers have been added to the home-page

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Also, resolve conflicts.

**Comment by pAditya198** [comment]
changing previous speakers from assests will be more easier  than using firebase.
I think this way is better bacause we are only displaying profile image.

Also Resolved Conflicts.

**Comment by pAditya198** [comment]
Also Fixed Overflow in About page

**Comment by aashutoshrathi** [comment]
Conflicts again.

**Comment by pAditya198** [comment]
@aashutoshrathi merge this PR I've fixed footer for mobile view and also fixed assets on speaker page and team page.

**Comment by aashutoshrathi** [comment]
@pAditya198 If there is anything in this PR that is missing please raise a new PR for the same.

**Comment by pAditya198** [comment]
I'm working on login page if there are any such changes i'll add it to that PR.

**Pull request closed without merging**
