### PR TITLE
making mobile ready ✔

### PR DESCRIPTION
**Pull request by AmanRaj1608**
#43

### CODE REVIEW

**Comment by AmanRaj1608** [comment]
Pixel 2 view

image

**Comment by aashutoshrathi** [comment]
This can be improved further right?

**Comment by AmanRaj1608** [comment]
@aashutoshrathi Yes Anuj said he has done something already. Waiting for him.

**Comment by anujpuri72** [comment]
@AmanRaj1608 done bro 🤘

**Comment by aashutoshrathi** [comment]
Please resolve conflicts.

**Comment by AmanRaj1608** [comment]
PLease see #47

**Pull request closed without merging**
