### PR TITLE
[WIP] Sign-in page created. 

### PR DESCRIPTION
**Pull request by pAditya198**
Screenshot (97)

This page has been routed.

### CODE REVIEW

**Comment by pAditya198** [comment]
@aashutoshrathi @thepushkarp @rossoskull  plx review

**Comment by thepushkarp** [comment]
The Sign In button:
image

After Signing In:
image

User Profile Page:
image

**Comment by thepushkarp** [comment]
@aashutoshrathi  @parth181195 @rossoskull Please review the changes.

@pAditya198  would be adding the design improvements such as the profile icon after login in topbar and other changes in the profile page.

**Comment by pAditya198** [comment]
Web view
changed simple signed in to user profile image.

Screenshot (112)

mobile view for the same.

Screenshot (113)

Signed in page.

Screenshot (114)

@aashutoshrathi  @thepushkarp @rossoskull  please review.

**Pull request merged**
