### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by samagragupta**
Minor Updates:

- on hover changes on buttons on the homepage and the signup button
- made color consistent for app-homepage-title's bar 
- About page images
- Uniform margin in each section of the homepage also for each partner's section
- Reduce the height of gdg logo
- Moved the content of the footer at the center
- Removed underline from anchor tag link of partners

### CODE REVIEW

**Comment by samagragupta** [comment]
@aashutoshrathi Please review.

**Comment by samagragupta** [comment]
@aashutoshrathi Done

**Comment by aashutoshrathi** [comment]
One more time.

**Comment by samagragupta** [comment]
@aashutoshrathi Done

**Pull request merged**
